-- US-01 en Oracle (12c+): los seis criterios de aceptación

-- Criterio 1: tabla sin relaciones
CREATE TABLE product (
  id          NUMBER(19)        GENERATED BY DEFAULT ON NULL AS IDENTITY,
  sku         VARCHAR2(32 CHAR) NOT NULL,
  name        VARCHAR2(255)     NOT NULL,
  description CLOB,
  price       NUMBER(10,2)      DEFAULT 0 NOT NULL,
  active      NUMBER(1)         DEFAULT 1 NOT NULL,
  created_at  TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT product_pk PRIMARY KEY (id),
  CONSTRAINT product_sku_uk UNIQUE (sku)
);

COMMENT ON TABLE product IS 'Productos del catálogo';
COMMENT ON COLUMN product.sku IS q'[Código interno (no se reutiliza)]';

-- Criterio 2: dos tablas relacionadas por FK
CREATE TABLE customer (
  id    NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  email VARCHAR2(255) NOT NULL
);

CREATE TABLE purchase_order (
  id          NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  customer_id NUMBER(10) NOT NULL,
  ordered_on  DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT order_customer_fk FOREIGN KEY (customer_id) REFERENCES customer (id) ON DELETE CASCADE
);

-- Criterio 3: uno a uno por FK única y por PK compartida
CREATE TABLE customer_settings (
  id          NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  customer_id NUMBER(10) NOT NULL
              CONSTRAINT settings_customer_uk UNIQUE
              CONSTRAINT settings_customer_fk REFERENCES customer,
  theme       VARCHAR2(20) DEFAULT 'light'
);

CREATE TABLE customer_profile (
  customer_id NUMBER(10) PRIMARY KEY REFERENCES customer (id),
  bio         VARCHAR2(4000)
);

-- Criterio 4: tabla intermedia pura
CREATE TABLE tag (
  id   NUMBER(10) PRIMARY KEY,
  name VARCHAR2(50) NOT NULL
);

CREATE TABLE product_tag (
  product_id NUMBER(19) NOT NULL REFERENCES product (id),
  tag_id     NUMBER(10) NOT NULL REFERENCES tag (id),
  CONSTRAINT product_tag_pk PRIMARY KEY (product_id, tag_id)
) ORGANIZATION INDEX;

-- Criterio 5: tabla intermedia con atributos propios
CREATE TABLE order_line (
  order_id   NUMBER(10)   NOT NULL,
  product_id NUMBER(19)   NOT NULL,
  quantity   NUMBER(5)    DEFAULT 1 NOT NULL,
  unit_price NUMBER(10,2) NOT NULL,
  CONSTRAINT order_line_pk PRIMARY KEY (order_id, product_id),
  CONSTRAINT order_line_order_fk FOREIGN KEY (order_id) REFERENCES purchase_order (id),
  CONSTRAINT order_line_product_fk FOREIGN KEY (product_id) REFERENCES product (id)
);

-- Criterio 6: clave primaria compuesta referenciada por una FK compuesta
CREATE TABLE warehouse (
  country_code CHAR(2 BYTE)  NOT NULL,
  code         VARCHAR2(10)  NOT NULL,
  name         VARCHAR2(100) NOT NULL,
  CONSTRAINT warehouse_pk PRIMARY KEY (country_code, code)
);

CREATE TABLE stock_item (
  country_code   CHAR(2 BYTE) NOT NULL,
  warehouse_code VARCHAR2(10) NOT NULL,
  product_id     NUMBER(19)   NOT NULL,
  quantity       NUMBER(*,0)  DEFAULT 0 NOT NULL,
  CONSTRAINT stock_item_pk PRIMARY KEY (country_code, warehouse_code, product_id),
  CONSTRAINT stock_warehouse_fk FOREIGN KEY (country_code, warehouse_code)
    REFERENCES warehouse (country_code, code)
);
