import { describe, expect, it } from 'vitest';
import { detectDialect } from './dialectDetection';

describe('detectDialect', () => {
  it.each([
    ['CREATE TABLE `a` (id INT AUTO_INCREMENT) ENGINE=InnoDB;', 'mysql'],
    ['CREATE TABLE a (id SERIAL, data JSONB);', 'postgresql'],
    ["ALTER TABLE ONLY a ALTER COLUMN id SET DEFAULT nextval('a_seq'::regclass);", 'postgresql'],
    ['CREATE TABLE a (id INTEGER PRIMARY KEY AUTOINCREMENT) WITHOUT ROWID;', 'sqlite'],
    ['CREATE TABLE a (id NUMBER(10), name VARCHAR2(50));', 'oracle'],
    ['CREATE TABLE a (created DATE DEFAULT SYSDATE);', 'oracle'],
    ['CREATE TABLE a (id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY);', 'oracle'],
    ['CREATE TABLE a (id INTEGER)\n/\n', 'oracle'],
    ['CREATE TABLE "HR"."A" ("ID" NUMBER(6,0) NOT NULL ENABLE) SEGMENT CREATION IMMEDIATE;', 'oracle'],
  ])('%s → %s', (sql, dialect) => {
    expect(detectDialect(sql)).toBe(dialect);
  });

  it('devuelve null si no hay rasgos propios de ningún dialecto', () => {
    expect(detectDialect('CREATE TABLE a (id INTEGER PRIMARY KEY, name VARCHAR(10));')).toBeNull();
  });

  it('devuelve null si hay empate', () => {
    expect(detectDialect('CREATE TABLE a (id INT AUTO_INCREMENT, b SERIAL);')).toBeNull();
  });

  it('los rasgos que PostgreSQL comparte con Oracle no desempatan a favor de PostgreSQL', () => {
    expect(
      detectDialect("CREATE TABLE a (id NUMBER(10), at TIMESTAMP WITH TIME ZONE);\nCOMMENT ON TABLE a IS 'x';"),
    ).toBe('oracle');
    expect(detectDialect('CREATE TABLE a (id BIGSERIAL, at TIMESTAMP WITH TIME ZONE);')).toBe('postgresql');
  });
});
