/**
 * Adaptador de `@khanakia/sql-schema-core`: el único fichero del proyecto que
 * importa la librería.
 *
 * Se usa para leer las definiciones de columna (nombre, tipo, nulabilidad,
 * valor por defecto y comentarios `--`). Las restricciones, los ALTER TABLE y
 * los diagnósticos los resuelve el propio parser, porque la librería pierde
 * información: separa las FK compuestas, fusiona las UNIQUE compuestas, ignora
 * los ALTER TABLE que no son FK y no informa de posiciones ni fragmentos.
 *
 * A la librería se le pasa una tabla sintética con el cuerpo original para
 * que el nombre real de la tabla (con comillas, espacios o esquema) no influya.
 */
import { parseSchema, type Column } from '@khanakia/sql-schema-core';
import type { SqlDialect } from '@/core/model';

export interface LibraryColumn {
  readonly name: string;
  /** `null` si la librería no ha reconocido el tipo. */
  readonly type: string | null;
  readonly nullable: boolean;
  readonly defaultValue?: string;
  readonly comment?: string;
}

export interface LibraryTableBody {
  readonly columns: readonly LibraryColumn[];
  /** Comentarios `--` situados antes de la primera columna. */
  readonly comment?: string;
}

const SYNTHETIC_TABLE = '__sqlparser_table__';

/**
 * En Oracle `#` es parte de los identificadores (`ORDER#`), pero la librería
 * lo trata como comentario. Se sustituye por un carácter de uso privado de
 * Unicode, que la librería trata como uno más del identificador, y se restaura
 * en la salida.
 */
const HASH_PLACEHOLDER = '';
const HASH_PLACEHOLDER_PATTERN = new RegExp(HASH_PLACEHOLDER, 'g');

/**
 * `GENERATED BY DEFAULT [ON NULL] AS IDENTITY` no es un valor por defecto, pero
 * la librería (que busca `default` sin límite de palabra) leería `DEFAULT AS`.
 * Se elimina la cláusula: la identidad la detecta el parser en el texto original.
 */
const IDENTITY_CLAUSE = /\bGENERATED\s+(?:ALWAYS|BY\s+DEFAULT)(?:\s+ON\s+NULL)?\s+AS\s+IDENTITY\b/gi;
/** `DEFAULT ON NULL [FOR INSERT …] expr` (Oracle) → `DEFAULT expr`: la librería leería `ON` como valor. */
const ORACLE_DEFAULT_ON_NULL = /\bDEFAULT\s+ON\s+NULL\s+(?:FOR\s+INSERT\s+(?:ONLY|AND\s+UPDATE)\s+)?/gi;

/** Lee las columnas del cuerpo de un CREATE TABLE (lo que va entre paréntesis). */
export function readTableBody(body: string, dialect: SqlDialect | null): LibraryTableBody | null {
  const source = prepareSource(body, dialect);
  // El salto de línea evita que un comentario `--` final se coma el paréntesis de cierre.
  const [table] = parseSchema(`CREATE TABLE ${SYNTHETIC_TABLE} (${source}\n)`).tables;
  if (!table) return null;

  return {
    columns: table.columns.map(toLibraryColumn),
    ...(table.comment ? { comment: restoreHashes(table.comment) } : {}),
  };
}

/** Lee una definición de columna suelta (`ADD COLUMN …`, `MODIFY …`). */
export function readColumnDefinition(definition: string, dialect: SqlDialect | null): LibraryColumn | null {
  return readTableBody(definition, dialect)?.columns[0] ?? null;
}

function prepareSource(text: string, dialect: SqlDialect | null): string {
  const source = text.replace(IDENTITY_CLAUSE, ' ');
  switch (dialect) {
    case 'mysql':
      return normalizeBackslashEscapes(source);
    case 'oracle':
      return source.replace(/#/g, HASH_PLACEHOLDER).replace(ORACLE_DEFAULT_ON_NULL, 'DEFAULT ');
    default:
      return source;
  }
}

function restoreHashes(text: string): string {
  return text.replace(HASH_PLACEHOLDER_PATTERN, '#');
}

function toLibraryColumn(column: Column): LibraryColumn {
  return {
    name: restoreHashes(column.name),
    type: column.type === '?' ? null : restoreHashes(column.type),
    nullable: column.nullable,
    ...(column.default !== undefined ? { defaultValue: restoreHashes(column.default) } : {}),
    ...(column.comment ? { comment: restoreHashes(column.comment) } : {}),
  };
}

/**
 * La librería no entiende los escapes con barra invertida de MySQL (`'it\'s'`).
 * Se reescriben como comillas duplicadas (`'it''s'`), con la misma longitud.
 */
function normalizeBackslashEscapes(text: string): string {
  let result = '';
  let quote: string | null = null;

  for (let i = 0; i < text.length; i++) {
    const c = text.charAt(i);
    const next = text.charAt(i + 1);

    if (quote) {
      if (c === '\\') {
        result += next === quote ? quote + quote : c + next;
        i++;
        continue;
      }
      if (c === quote) quote = null;
      result += c;
      continue;
    }

    if ((c === '-' && next === '-') || c === '#') {
      const stop = text.indexOf('\n', i);
      const end = stop < 0 ? text.length : stop;
      result += text.slice(i, end);
      i = end - 1;
      continue;
    }
    if (c === "'" || c === '"') quote = c;
    result += c;
  }
  return result;
}
